language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - ci/Gemfile-rails-3-0
  - ci/Gemfile-rails-3-1
  - ci/Gemfile-rails-3-2
  - ci/Gemfile-rails-4-0
  - ci/Gemfile-rails-4-1
  - ci/Gemfile-rails-4-2
before_install: gem update bundler
sudo: false
env:
  - DB=sqlite
  - DB=mysql
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS unread_test;'; fi"
